sistema/project/urls.py
from django.urls import path, include
from django.contrib.auth import views
from django.contrib import admin
from project import views
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('veiculo/', include('veiculo.urls'), name='veiculo'),
]

sistema/veiculo/urls.py
from django.urls import path, include
from veiculo.views import *
urlpatterns = [
    path('', ListarVeiculos.as_view(), name='listar_veiculos'),
]

sistema/veiculo/models.py
from django.db import models
from veiculo.consts import *

class Veiculo(models.Model):
    combustivel = models.SmallIntegerField(choices=OPCOES_COMBUSTIVEIS, verbose_name='Combustível')
    modelo = models.CharField(max_length=100, verbose_name='Modelo')
    marca = models.SmallIntegerField(choices=OPCOES_MARCAS, verbose_name='Marca')
    cor = models.SmallIntegerField(choices=OPCOES_CORES, verbose_name='Cor')
    ano = models.IntegerField(verbose_name='Ano')
    # foto = models.ImageField(upload_to='veiculos/', verbose_name='Foto', blank=True, null=True)

    class Meta:
        verbose_name = 'Veículo'
        verbose_name_plural = 'Veículos'
        ordering = ['modelo']
        db_table = 'veiculos'

sistema/project/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth import authenticate, login, logout

from django.conf import settings

class Index(View):
    def get(self, request):
        if not request.user.is_authenticated:  
            return redirect('login')
        else:
            return redirect('listar_veiculos')
        # return render(request, 'index.html')

class Login(View):
    def get(self, request):

        if request.user.is_authenticated:  
            return redirect('index')

        context = {
            'title': 'Login',
        }

        return render(request, 'login.html', context)
    
    def post(self, request):

        mensagem = {}

        username = request.POST.get('username', None)
        password = request.POST.get('password', None)

        user = authenticate(request, username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('listar_veiculos')
            mensagem['tag'] = 'danger'
            mensagem['content'] = 'Usuário inativo.'
            return render(request, 'login.html', {'mensagem': mensagem})
        else:
            mensagem['tag'] = 'danger'
            mensagem['content'] = 'Usuário ou senha incorretos.'
            return render(request, 'login.html', {'mensagem': mensagem})

class Logout(View):
    def get(self, request):
        logout(request)
        return redirect(settings.LOGIN_URL)
    def post(self, request):
        pass

sistema/veiculo/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views import View
from veiculo.models import *

# ListView é um mixin que permite listar objetos de um modelo

class ListarVeiculos(ListView):
    model = Veiculo
    context_object_name = 'veiculos'
    template_name = 'veiculos/listar.html'

sistema/templates/layouts/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>{% block title %}{% endblock %}</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet">

   <!-- Font Awesome -->
   <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
   <!-- Google Fonts -->
   <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
   <!-- Bootstrap -->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" defer></script>
   <!-- MD Bootstrap -->
   <link href="{% static 'mdb5-free-standard/css/mdb.min.css' %}" rel="stylesheet" type="text/css"/>

   <link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css"/>

   {% block extra_links %}
   {% endblock %}
</head>
<body>
   {% block content %}
   {% endblock %}
        
   <script src="{% static 'mdb5-free-standard/js/mdb.umd.min.js' %}"></script>
   <script src="{% static 'js/scripts.js' %}"></script>

   {% block extra_scripts %}
   {% endblock %}
</body>
</html>

sistema/templates/login.html
{% extends 'layouts/_base.html' %}

{% load static %}

{% block title %}Login{% endblock %}

{% block content %}

{% include 'partials/login-navbar.html' %}
   <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
         <div class="col-md-9 col-lg-6 col-xl-5">
            <!-- <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp" class="img-fluid" alt="Sample image"> -->
            {% include 'partials/login-img.html' %}
         </div>
         <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
            {% if mensagem %}
            <div class="alert alert-{{ mensagem.tag }}" role="alert">
               {{ mensagem.content }}
            </div>
            {% endif %}
            <form id="login-form" action="{% url 'login' %}" method="POST" name="login-form">
               {% csrf_token %}
               <div class="d-flex flex-row align-items-center justify-content-center text-center justify-content-lg-center">
                  <p class="lead fw-normal mb-0 me-3">Entre com</p>
                  <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-custom btn-floating mx-1">
                     <i class="fab fa-facebook-f"></i>
                  </button>

                  <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-custom btn-floating mx-1">
                     <i class="fab fa-google"></i>
                  </button>

                  <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-custom btn-floating mx-1">
                     <i class="fab fa-linkedin-in"></i>
                  </button>
               </div>

               <div class="divider d-flex align-items-center my-4">
                  <p class="text-center fw-bold mx-3 mb-0">ou</p>
               </div>

               <!-- Username input -->
               <div data-mdb-input-init class="form-outline mb-4">
                  <input name="username" type="text" id="form3Example3" class="form-control form-control-lg"
                     placeholder="Digite um nome de usuário" />
                  <label class="form-label" for="form3Example3">Nome de Usuário</label>
               </div>

               <!-- Password input -->
               <div data-mdb-input-init class="form-outline mb-3">
                  <input name="password" type="password" id="form3Example4" class="form-control form-control-lg"
                     placeholder="Digite uma senha" />
                  <label class="form-label" for="form3Example4">Senha</label>
               </div>

               <!-- Checkbox -->
               <!-- <div class="d-flex justify-content-between align-items-center">
                  <div class="form-check mb-0">
                     <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
                     <label class="form-check-label" for="form2Example3">
                        Lembrar de mim
                     </label>
                  </div>
                  <a href="#!" class="text-body">Esqueceu a senha?</a>
               </div> -->

               <div class="text-center text-lg-start mt-4 pt-2">
                  <!-- <button id="button-form" type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-custom btn-lg"
                     style="padding-left: 2.5rem; padding-right: 2.5rem;">
                     Entrar
                  </button> -->

                  <button id="button-form" type="submit" class="btn btn-custom btn-lg"
                     style="padding-left: 2.5rem; padding-right: 2.5rem;">
                     Entrar
                  </button>
                  <p class="small fw-bold mt-2 pt-1 mb-0">Não possui uma conta?
                     <a href="#!" class="link-danger" style="color: var(--main-color) !important;">Criar conta</a>
                  </p>
               </div>
            </form>
         </div>
      </div>
   </div>
{% include 'partials/footer.html' %}

{% endblock %}

sistema/templates/partials/footer.html
{% load static %}

<footer class="text-center bg-body-tertiary">
    <!-- Grid container -->
    <div class="container pt-4">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a
          data-mdb-ripple-init
          class="btn btn-link btn-floating btn-lg text-body m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-facebook-f"></i
        ></a>
  
        <!-- Twitter -->
        <a
          data-mdb-ripple-init
          class="btn btn-link btn-floating btn-lg text-body m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-twitter"></i
        ></a>
  
        <!-- Google -->
        <a
          data-mdb-ripple-init
          class="btn btn-link btn-floating btn-lg text-body m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-google"></i
        ></a>
  
        <!-- Instagram -->
        <a
          data-mdb-ripple-init
          class="btn btn-link btn-floating btn-lg text-body m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-instagram"></i
        ></a>
  
        <!-- Linkedin -->
        <a
          data-mdb-ripple-init
          class="btn btn-link btn-floating btn-lg text-body m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-linkedin"></i
        ></a>
        <!-- Github -->
        <a
          data-mdb-ripple-init
          class="btn btn-link btn-floating btn-lg text-body m-1"
          href="#!"
          role="button"
          data-mdb-ripple-color="dark"
          ><i class="fab fa-github"></i
        ></a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2020 Copyright:
      <a class="text-body" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>

sistema/templates/partials/login-img.html
<svg class="w-100 h-auto" xmlns="http://www.w3.org/2000/svg" width="901.08774" height="624" viewBox="0 0 901.08774 624" xmlns:xlink="http://www.w3.org/1999/xlink" role="img" artist="Katerina Limpitsouni" source="https://undraw.co/">
    <circle cx="425" cy="293" r="293" fill="#e6e6e6" stroke-width="0"/>
    <path d="m693.81633,93.37235c-.7161,1.6475-1.46513,3.27738-2.24611,4.88892-63.77801,2.56127-164.63218,5.61343-233.1492,2.604-.4141-.80852-.82023-1.62158-1.21823-2.43917-4.30371-8.8408,2.74425-19.01754,12.51639-17.92801l.22835.02553s12.80688-38.42064,46.95856-27.74824c0,0,76.84128-120.32036,151.54807,7.08662,0,0,.42333-.07649,1.2114-.14626,18.09291-1.60185,31.39139,16.9985,24.15078,33.65661Z" fill="#fff" stroke-width="0"/>
    <rect x="704.5" y="275.5" width="38" height="329" fill="#2f2e43" stroke-width="0"/>
    <path d="m840.4971,610.38435c-2.36081-13.48354-5.26636-27.0211-11.08192-39.41298-5.81556-12.39187-14.81323-23.67707-26.93319-30.0399-19.00679-9.97834-44.50251-5.46228-58.92552,10.43747-14.42301,15.89975-16.44023,41.71366-4.6622,59.66089" fill="#e6e6e6" stroke-width="0"/>
    <path d="m742.74988,612.01543c-1.96558-24.77358-15.46333-48.79102-36.65984-61.76414s-49.77906-13.76498-70.74036-.41514-32.37785,40.85949-25.35371,64.6976" fill="#e6e6e6" stroke-width="0"/>
    <path d="m901.08774,611.40652c-4.31433-16.47012-18.78124-29.81691-35.54495-32.79285-8.216-1.45853-17.56384-.21574-23.28132,5.86212-7.01074,7.45263-6.24592,19.0772-5.03265,29.23693" fill="#e6e6e6" stroke-width="0"/>
    <circle cx="425" cy="251" r="129" fill="#ff6363" stroke-width="0"/>
    <path d="m900.91283,611.7391c0,5.52285-392.53958,12.2609-573.41283,12.2609S0,619.52285,0,614s146.62674-10,327.5-10,573.41283,2.21626,573.41283,7.7391Z" fill="#e6e6e6" stroke-width="0"/>
    <polygon points="69.4789 509.48252 78 543 161.68325 557.5 161.68325 493.59697 69.4789 489.5 69.4789 509.48252" fill="#2f2e43" stroke-width="0"/>
    <rect x="155" y="473" width="427" height="100" fill="#2f2e43" stroke-width="0"/>
    <path d="m176,560c0,28.16652-10.83333,51-47.5,51-31.66667,0-42.5-22.83348-42.5-51s16.26647-51,42.5-51,47.5,22.83348,47.5,51Z" fill="#2f2e43" stroke-width="0"/>
    <ellipse cx="116" cy="557.5" rx="20" ry="39.5" fill="#fff" stroke-width="0"/>
    <circle cx="116" cy="554" r="14" fill="#2f2e43" stroke-width="0"/>
    <ellipse cx="576" cy="550" rx="57" ry="64" fill="#2f2e43" stroke-width="0"/>
    <ellipse cx="306" cy="556" rx="44" ry="48" fill="#2f2e43" stroke-width="0"/>
    <ellipse cx="386" cy="560" rx="57" ry="64" fill="#2f2e43" stroke-width="0"/>
    <ellipse cx="375.5" cy="556" rx="35.5" ry="47" fill="#fff" stroke-width="0"/>
    <circle cx="375" cy="550" r="19" fill="#2f2e43" stroke-width="0"/>
    <path d="m48.5,527.82823v-76.10193c0-6.68131,5.41627-12.09758,12.09758-12.09758h16.14697s13.25545-79.62872,38.25545-90.62872,249-61,372-12l41,75s93,0,103,21c0,0,44-11,48,37l-11,56-4,20-217-7-40-5s-6-46-35-46-41,7-41,7c0,0-22,36-15,72h-162.94161s-7.05839-56-40.05839-57c-15.0264-.45535-30-6-35,33l-17.90952-2.12486c-6.61102-.78436-11.59048-6.38953-11.59048-13.04692Z" fill="var(--main-color)" stroke-width="0"/>
    <path d="m520.34789,410.49985h-195.64551c-6.44775,0-11.875-4.62012-12.90527-10.98486l-7.36572-45.53418c-.52881-3.27148.29785-6.51318,2.32861-9.12842,2.02881-2.61279,4.96045-4.21484,8.25586-4.51221,106.33057-9.59375,149.72266-2.64648,163.44336.78516,8.42334,2.10645,15.50684,8.1333,18.94824,16.12158l22.94043,53.25293Z" fill="#fff" stroke-width="0"/>
    <path d="m237.80444,419.64535c-1.5708,0-3.10596-.03223-4.60156-.10107-2.51709-.11572-4.86719-1.30225-6.44775-3.25537-1.57129-1.94189-2.23828-4.46973-1.82959-6.93506l7.92725-47.85645c.62891-3.79639,3.73438-6.78271,7.55127-7.2627l38.08154-4.79297c4.50049-.56836,8.65137,2.34668,9.64502,6.77783l10.24316,45.69434c.51318,2.28857.104,4.63867-1.15234,6.61768-1.25391,1.9751-3.20215,3.34326-5.48584,3.85156-12.62207,2.80908-35.53613,7.26172-53.93115,7.26221Z" fill="#fff" stroke-width="0"/>
    <path d="m128.06664,428.77963c-2.37891,0-4.63672-1.0835-6.12402-2.96436-1.59912-2.02197-2.09521-4.69922-1.32764-7.16162,6.13428-19.66797,17.43262-53.11084,24.18213-56.11084,6.72168-2.9873,41.37256-5.64746,61.42969-6.96729,2.39648-.1543,4.69434.7749,6.30273,2.55811,1.61084,1.78564,2.30273,4.16992,1.89893,6.54199l-8.97217,52.74463c-.60596,3.56299-3.54736,6.22705-7.15283,6.47852l-69.69092,4.8623c-.18213.0127-.36475.01855-.5459.01855Z" fill="#fff" stroke-width="0"/>
    <polygon points="197 550 197 450.84003 211.85346 429 306.20602 429 293 455 296.04498 550 197 550" fill="none" stroke="#2f2e43" stroke-linecap="round" stroke-miterlimit="10"/>
    <line x1="166.7412" y1="550" x2="197" y2="550" fill="none" stroke="#2f2e43" stroke-linecap="round" stroke-miterlimit="10"/>
    <path d="m102.25489,509.48252s5.74511-67.47928,15.74511-70.9809l84-6.50162" fill="none" stroke="#2f2e43" stroke-linecap="round" stroke-miterlimit="10"/>
    <line x1="123" y1="462" x2="136.3714" y2="462" fill="none" stroke="#2f2e43" stroke-linecap="round" stroke-miterlimit="10"/>
    <rect x="206.77293" y="450.11424" width="17.22707" height="7.88576" fill="none" stroke="#2f2e43" stroke-linecap="round" stroke-miterlimit="10"/>
    <path d="m306.20602,429l176.29398-6.5s21.4023,11.48252,26.20115,48.24126l118.79885,4.75874s11-27,3.5-42.5" fill="none" stroke="#2f2e43" stroke-linecap="round" stroke-miterlimit="10"/>
    <circle cx="474" cy="473" r="23" fill="#2f2e43" stroke-width="0"/>
    <circle cx="474" cy="473" r="17" fill="#fff" stroke-width="0"/>
    <ellipse cx="663.5" cy="477.5" rx="18" ry="22" fill="#2f2e43" stroke-width="0"/>
    <ellipse cx="662" cy="478" rx="12" ry="18" fill="#fff" stroke-width="0"/>
    <ellipse cx="470.5" cy="508" rx="6" ry="8.5" fill="#fff" stroke-width="0"/>
    <ellipse cx="660" cy="516" rx="5" ry="8" fill="#fff" stroke-width="0"/>
    <path d="m642,517h-145l3-20.43277c0-10.80668,8.76055-19.56723,19.56723-19.56723h102.06411c11.2493,0,20.36866,9.11936,20.36866,20.36866v19.63134Z" fill="#2f2e43" stroke-width="0"/>
    <path d="m709.95494,315.8501s-54.45494-7.38951-35.95494-74.36981h7.5s-9,34.01971,26,51.01971l2.45494,23.3501Z" fill="#2f2e43" stroke-width="0"/>
    <path d="m739.5,338.5s35-48,35-67h-9.66817s-9.47127,29-30.90155,33.5l5.56972,33.5Z" fill="#2f2e43" stroke-width="0"/>
    <path d="m648.55758,267.76115c-1.88105,14.64425-17.07902,25.44128-31.8252,24.70468-14.74618-.73659-27.89553-11.27348-34.30491-24.57431s-6.79627-28.87606-3.83867-43.34136c-14.83675-19.96988-23.43506-44.50715-24.30853-69.37002-.47906-13.63633,1.64142-28.12783,10.26209-38.70436,6.91025-8.47805,17.74025-13.62087,28.67775-13.61816s21.76495,5.15091,28.67099,13.63238l-1.87434-.22424c-1.69628-13.68469-3.39489-27.50677-2.01779-41.22725s6.11615-27.52861,15.71654-37.42712c9.88278-10.18967,23.82911-15.27587,37.53118-18.98428,19.91186-5.38905,41.04444-8.53752,61.12158-3.80123s38.92927,18.65177,44.94536,38.38323c15.83791-.57463,32.26505,1.18973,46.07832,8.95912,13.81327,7.76938,24.48078,22.5371,23.85478,38.37307-.62599,15.83597-15.075,30.86946-30.81686,29.03541,10.22069,6.54369,20.25733,13.78441,27.59861,23.44816,7.34128,9.66374,11.74254,22.14775,9.4097,34.05741-2.33284,11.90967-12.52366,22.55005-24.64852,23.06973l-2.65531,1.36037c14.59379,13.63762,14.0782,38.66701,2.15762,54.69397-11.92058,16.02696-32.43661,23.82266-52.37934,24.94117s-39.70214-3.5792-59.12383-8.24411c-22.71134-5.45506-45.42268-10.91012-68.13402-16.36518l-.09721,1.22292Z" fill="var(--main-color)" stroke-width="0"/>
    <path d="m351.88506,97.01872c-.33549.77185-.68641,1.53545-1.0523,2.29045-29.87988,1.19995-77.12988,2.62988-109.22998,1.21997-.194-.37879-.38428-.75971-.57074-1.14275-2.01628-4.1419,1.28568-8.90968,5.8639-8.39924l.10698.01196s6-18,22-13c0,0,36-56.36987,71,3.32007,0,0,.19833-.03583.56754-.06852,8.47649-.75046,14.70681,7.96377,11.3146,15.76806Z" fill="#fff" stroke-width="0"/>
    <path d="m324.81633,250.37235c-.7161,1.6475-1.46513,3.27738-2.24611,4.88892-63.77801,2.56127-164.63218,5.61343-233.1492,2.604-.4141-.80852-.82023-1.62158-1.21823-2.43917-4.30371-8.8408,2.74425-19.01754,12.51639-17.92801l.22835.02553s12.80688-38.42064,46.95856-27.74824c0,0,76.84128-120.32036,151.54807,7.08662,0,0,.42333-.07649,1.2114-.14626,18.09291-1.60185,31.39139,16.9985,24.15078,33.65661Z" fill="#fff" stroke-width="0"/>
</svg>

sistema/templates/partials/login-navbar.html
{% load static %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <!-- Container wrapper -->
    <div class="container">
      <!-- Navbar brand -->
      <a class="navbar-brand me-2" data-mdb-ripple-init href="{% url 'index' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="var(--main-color)" class="bi bi-car-front-fill" viewBox="0 0 16 16">
          <path d="M2.52 3.515A2.5 2.5 0 0 1 4.82 2h6.362c1 0 1.904.596 2.298 1.515l.792 1.848c.075.175.21.319.38.404.5.25.855.715.965 1.262l.335 1.679q.05.242.049.49v.413c0 .814-.39 1.543-1 1.997V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.338c-1.292.048-2.745.088-4 .088s-2.708-.04-4-.088V13.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-1.892c-.61-.454-1-1.183-1-1.997v-.413a2.5 2.5 0 0 1 .049-.49l.335-1.68c.11-.546.465-1.012.964-1.261a.8.8 0 0 0 .381-.404l.792-1.848ZM3 10a1 1 0 1 0 0-2 1 1 0 0 0 0 2m10 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2M6 8a1 1 0 0 0 0 2h4a1 1 0 1 0 0-2zM2.906 5.189a.51.51 0 0 0 .497.731c.91-.073 3.35-.17 4.597-.17s3.688.097 4.597.17a.51.51 0 0 0 .497-.731l-.956-1.913A.5.5 0 0 0 11.691 3H4.309a.5.5 0 0 0-.447.276L2.906 5.19Z"/>
        </svg>
      </a>
  
      <!-- Toggle button -->
      <button
        data-mdb-collapse-init
        class="navbar-toggler"
        type="button"
        data-mdb-target="#navbarButtonsExample"
        aria-controls="navbarButtonsExample"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
  
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarButtonsExample">
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'index' %}">Projeto DevWeb Django</a>
          </li>
        </ul>
        <!-- Left links -->
  
        <div class="d-flex align-items-center">
          <a href="{% url 'login' %}" data-mdb-ripple-init class="btn btn-link px-3 me-2 {% if request.path == '/login/' %}disabled{% endif %}">
            Entrar
          </a>
          <a href="{% url 'index' %}" data-mdb-ripple-init class="btn btn-custom me-3">
            Cadastre-se
          </a>
        </div>
      </div>
      <!-- Collapsible wrapper -->
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->

sistema/templates/veiculos/listar.html
{% extends 'layouts/_base.html' %}

{% load static %}

{% block title %}Listar Veiculos{% endblock %}

{% block content %}

{% include 'partials/navbar.html' %}

<div class="container w-100">
    <div class="card-group pt-5">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
            {% for veiculo in veiculos %}
            <div class="col">
                <div class="card px-3">
                    <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" class="card-img-top" alt="Hollywood Sign on The Hill"/>
                    <div class="card-body">
                    <h5 class="card-title">{{veiculo.modelo}}</h5>
                    <p class="card-text">
                        {{veiculo.modelo}}
                        {{veiculo.get_marca_display}}
                        {{veiculo.get_combustivel_display}}
                    </p>
                    <p class="card-text">
                        <small class="text-muted">{{veiculo.ano}}</small>
                    </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% include 'partials/footer.html' %}

{% endblock %}